config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  root 'home#site_index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
	 devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def site_index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/site_index.html.erb
<h1>Welcome to the Photo App</h1>

<p><%= link_to('Share photos now!', new_member_registration_path) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <% if member_signed_in? %>
      <p><%= link_to('Sign out', destroy_member_session_path, method: :delete) %></p>
      <p><%= link_to('Settings', edit_member_registration_path(current_member)) %></p>
    <% else %>
      <p><%= link_to('Sign in', new_member_session_path) %></p>
  	<% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
    </body>
</html>